### ISSUE TITLE
port 5000 closed by default?

### ISSUE THREAD

**Issue by yssfbahri** [OWASP/IoTGoat#10]
upnp port 5000 seems to be closed. tired restarting the machine (VM in oracle virtual box). do I need to activate upnp service myself?
![issue](https://github.com/OWASP/IoTGoat/assets/138758418/71e61a2b-bd96-4c4e-a889-2950d8028fd1)

**Comment by scriptingxss** [comment]
Hi, no upnp is enabled on start. You might want to double check your network setup following the getting started page https://github.com/OWASP/IoTGoat/wiki/Getting-started. Afterward, try port scanning using commands described in the solutions page https://github.com/OWASP/IoTGoat/wiki/Challenge-solutions#no-2-insecure-network-services.
