### ISSUE TITLE
Unable to find iotgoathardcodedpassword file 

### ISSUE THREAD

**Issue by abhigyan17** [OWASP/IoTGoat#5]
Dear Team, 

Tried alot but unable to locate the file where hard coded password is kept.

**Comment by scriptingxss** [comment]
Hi @abhigyan17, 
If you are having a rough time and need some assistance finding solutions, please check out our wiki section :) Ill give you a hint, its in the `/etc/` directory

**Comment by scriptingxss** [comment]
IoTGoat's hardcoded credentials are MD5 hash values in `/etc/shadow` - https://github.com/OWASP/IoTGoat/blob/2d4343f8c4ce4a4bbb6cd3a33e2ebf9524651ac5/OpenWrt/openwrt-18.06.2/files/etc/shadow#L1
