### ISSUE TITLE
VM won't start

### ISSUE THREAD

**Issue by InspecteurKepler** [OWASP/IoTGoat#6]
Hello, idk why but i have an error when I start the VM on VirtualBox and VmWare Workstation Pro 16

Errors:
![image](https://user-images.githubusercontent.com/45036197/104342433-1de4f200-54fb-11eb-85f9-22e2125a48a5.png)
![image](https://user-images.githubusercontent.com/45036197/104342441-1faeb580-54fb-11eb-9930-54eaf8fb77bf.png)

**Comment by scriptingxss** [comment]
Have you tried following the virtualbox directions in https://github.com/OWASP/IoTGoat/wiki/Getting-started? You'll need to check the `Enable PAE/NX` box.

**Comment by InspecteurKepler** [comment]
I find the error since, it was because of Hyper-V
