### ISSUE TITLE
What is the password for the web

### ISSUE THREAD

**Issue by harry1080** [OWASP/IoTGoat#8]
What is the password of the web and how to find the password of the web

![image](https://user-images.githubusercontent.com/19358692/130009393-6e6b6b9b-07e7-4abe-95f1-db1b018a9e2c.png)

**Comment by tabacci** [comment]
login web as user root with the password **iotgoathardcodedpassword** 
![IoTGoat](https://user-images.githubusercontent.com/50152281/131452115-1bab0b43-ea92-4311-b965-5700d8ed70bb.jpg)

**Comment by scriptingxss** [comment]
Yep password details are in the following page https://github.com/OWASP/IoTGoat/wiki/Challenge-solutions#no-1-hardcoded-user-credentials-compiled-into-firmware
