### ISSUE TITLE
Not able to build from source

### ISSUE THREAD

**Issue by ivansimon319** [OWASP/IoTGoat#9]
Hello. I am facing an error while building from the source. The error is regarding absence of gcc and g++ but in my kali linux virtual machine I have gcc and g++ v13.1.0.  
<img width="570" alt="IoTGoat" src="https://github.com/OWASP/IoTGoat/assets/110600212/0156d407-2ad0-485b-b69f-ace6c5c20833">

**Comment by Xhoenix** [comment]
I was able to compile from source after a lot of troubleshooting and code patching. I'd recommend using the images from the IotGoat **Releases** for ease of use.

**Comment by Xhoenix** [comment]
For solution to the above problem, edit the file `./include/prereq-build.mk` from the directory you're in the image, and change the `gcc` and `g++` values to point to respective binaries on your system. For e.g. I added `gcc-9` and `g++-9` to the list and was able to solve the above bug. 

![image](https://github.com/OWASP/IoTGoat/assets/86168235/7c9e38c3-5220-4a92-9187-1f0f9f54306a)



&nbsp;
But, as I said there is a lot more troubleshooting to do after fixing the above.

**Comment by scriptingxss** [comment]
Its been awhile since building IoTGoat from source. Id recommend using Ubuntu over Kali for building but there might be toolchain updates that could cause conflicts which you both might be experiencing.

**Comment by a-Lucar-d** [comment]
@Xhoenix I luckily solved the gcc issue.
right now i am facing this while making menuconfig.
```bash
adityakrishna@a-lucard:~/kichu/owasp/IoTGoat/OpenWrt/openwrt-18.06.2$ make menuconfig
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-mesh-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-mesh-wolfssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-mini', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-wolfssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant-mesh-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant-mesh-wolfssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant-mini', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant-p2p', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant-wolfssl||', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_hostapd-mini', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_hostapd-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_hostapd-wolfssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-mesh-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-mesh-wolfssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-mini', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-wolfssl||', which does not exist
tmp/.config-package.in:86722: syntax error
tmp/.config-package.in:86721: invalid option
tmp/.config-package.in:90856: syntax error
tmp/.config-package.in:90855: invalid option
make: *** [/home/adityakrishna/kichu/owasp/IoTGoat/OpenWrt/openwrt-18.06.2/include/toplevel.mk:137: menuconfig] Error 1

```
I tried using the IOTgoat latest releases only.

**Comment by parsley72** [comment]
Running into the same problem. Any solution yet?

I was wondering about how the project was actually created. Would it be easier to migrate to a more recent version of OpenWRT then apply whatever changes were made?

**Comment by parsley72** [comment]
This fixed that problem: https://github.com/openwrt/openwrt/issues/7621

Now getting:
```
cd OpenWrt/openwrt-18.06.2/
  make menuconfig
  shell: /usr/bin/bash -e {0}
  
Error opening terminal: unknown.
make: *** [/home/runner/work/IoTGoat/IoTGoat/OpenWrt/openwrt-18.06.2/include/toplevel.mk:1[3]/actions/runs/11205172581/job/31144404680#step:7:3)7: menuconfig] Error 1
Error: Process completed with exit code 2.
```

**Comment by scriptingxss** [comment]
Buildchains are sensitive especially if youre updating host packages which cause issues when building for older platforms. I suggest using the VM, docker, or the compiled release images versus building if youre having trouble. If you happen to upgrade to a more recent Openwrt version and want to contribute to the project, I welcome PRs for these :) Closing as this will reoccur depending on the host build system.

**Comment by parsley72** [comment]
Where are the instructions for the VM or docker builds?

**Comment by scriptingxss** [comment]
> Where are the instructions for the VM or docker builds?

Check out https://github.com/OWASP/IoTGoat?tab=readme-ov-file#getting-started. I have a PR to review the docker build https://github.com/OWASP/IoTGoat/pull/11 but they should have a working version for you to try out

**Comment by parsley72** [comment]
I'm not seeing anything about builds here.

**Comment by parsley72** [comment]
https://github.com/OWASP/IoTGoat/pull/13
